declare let smartcli: any;
declare let should: any;
declare var checkCommandArgumentTest: () => void;
declare var checkCommandArgumentPresenceTest: () => void;
declare var getCommandTest: () => void;
declare var getCommandArgumentTest: () => void;
declare var getCommandArgsTest: () => void;
declare var getOptionTest: () => void;
declare var getCwdTest: () => void;
declare var interactionGetAnswerTest: () => void;
declare var interactionGetChoiceTest: () => void;
declare var endTests: () => void;
